Xtend Dark Theme
eclipse/xtext-xtend pull request #1138
Opened 2020-11-13 14:12 UTC by kthoms

Replaces https://github.com/eclipse/xtext-xtend/pull/1082. Left the initial commit to have the original contributor in the history.

Based on the initial proposal the theme changes are managed by listening on theme change events. Instead of the introduction of a new bundle this is managed by the introduced XtendThemeManager class.

While the approach did work for setting the dark theme, it failed when switching back to other themes (Light, System). I have added a stylesheet for the default theme that reflects the settings given by XtendHighlightingConfiguration, but it actually is not effective. This might be left as is, or be removed.

As a workaround when switching back from dark theme the preferences are overwritten with the configuration from XtendHighlightingConfiguration. It still causes a small hickup with keyword highlighting, which is gone after the recommended restart.

The implemented coloring scheme is based on the [Tomorrow Theme](https://github.com/chriskempson/tomorrow-theme/blob/master/Eclipse/Tomorrow-Night.epf).

<img width="1892" alt="Bildschirmfoto 2020-11-12 um 01 51 57" src="https://user-images.githubusercontent.com/265597/99080987-5e3ef700-25c2-11eb-977f-2b837f5e7ecd.png">

2020-11-13 15:17 UTC, cdietrich commented
@kthoms there are still build errors

2020-11-13 16:35 UTC, kthoms commented
Ah, version constraint. This is because I'm on latest target. Have to check with Oxygen.

2020-11-16 07:42 UTC, cdietrich commented on org.eclipse.xtend.ide/.classpath
> +	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins">
is this to suppress internal use warnings?

2020-11-16 07:43 UTC, cdietrich commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.java
> +		binder.bind(XtendThemeManager.class).asEagerSingleton();
wo we want to have this eager?

2020-11-16 07:44 UTC, cdietrich commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +	private static final String THEME_ID_DARK = "org.eclipse.e4.ui.css.theme.e4_dark";
why dont we need a light theme as well?

2020-11-17 05:44 UTC, kthoms commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +	private static final String THEME_ID_DARK = "org.eclipse.e4.ui.css.theme.e4_dark";
It isn't just light, but anything except for dark. There is also a System and Classic theme by default, and other themes could be added as well. Platform is missing currently a way to identify dark themes (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=564022).

We may search for the theme id containing "dark" instead of hard wire the default dark theme.

2020-11-17 05:44 UTC, kthoms commented on org.eclipse.xtend.ide/.classpath
> +	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins">
yes

2020-11-17 10:10 UTC, szarnekow commented on org.eclipse.xtend.ide/.classpath
> +	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins">
At all other places that I'm aware of we do use `@SuppressWarnings` - please keep that consistent.

2020-11-17 10:11 UTC, szarnekow commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java
> +		INSTANCE = null;
No unsubscribe?

2020-11-17 10:12 UTC, szarnekow commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java
> +	private static XtendActivator INSTANCE;
I don't think INSTANCE is necessary

2020-11-17 10:14 UTC, szarnekow requested changes
Some cleanup pending. Other than that it looks good so far. I'll need to test-drive this, though.

2020-11-17 10:15 UTC, szarnekow commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +				String colorKey = String.format("%s.%s.%s.%s.%s", ORG_ECLIPSE_XTEND_CORE_XTEND, SYNTAX_COLORER_PREFERENCE_TAG, TOKEN_STYLES_PREFERENCE_TAG, id, COLOR_SUFFIX);
Can we extract a method for the lengthy String.format invocations. It could have a descriptive name, too :)

2020-11-17 10:16 UTC, szarnekow commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +					preferences.put(colorKey, String.format("%d,%d,%d", color.red, color.green, color.blue));
Same here: `preferences.put(colorKey, encodeColor(color))` would read better

2020-11-18 21:44 UTC, kthoms commented on org.eclipse.xtend.ide/.classpath
> +	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins">
done

2020-11-18 21:44 UTC, kthoms commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java
> +	private static XtendActivator INSTANCE;
removed

2020-11-18 21:44 UTC, kthoms commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +				String colorKey = String.format("%s.%s.%s.%s.%s", ORG_ECLIPSE_XTEND_CORE_XTEND, SYNTAX_COLORER_PREFERENCE_TAG, TOKEN_STYLES_PREFERENCE_TAG, id, COLOR_SUFFIX);
done

2020-11-18 21:44 UTC, kthoms commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +					preferences.put(colorKey, String.format("%d,%d,%d", color.red, color.green, color.blue));
done

2020-11-20 09:17 UTC, szarnekow approved these changes

2020-11-20 09:21 UTC, cdietrich commented on org.eclipse.xtend.ide/META-INF/MANIFEST.MF
> +Bundle-Activator: org.eclipse.xtend.ide.XtendActivator
why this change

2020-11-20 09:22 UTC, cdietrich commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java
> +@SuppressWarnings("restriction")
what is restricted here?

2020-11-20 09:22 UTC, cdietrich commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +public class XtendThemeManager implements EventHandler {
what is restricted here?

2020-11-20 09:31 UTC, kthoms commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java
> +@SuppressWarnings("restriction")
IThemeEngine

2020-11-20 09:33 UTC, cdietrich commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java
> +@SuppressWarnings("restriction")
should we do a platform patch that adds us as xfriends?

2020-11-20 12:34 UTC, kthoms commented on org.eclipse.xtend.ide/META-INF/MANIFEST.MF
> +Bundle-Activator: org.eclipse.xtend.ide.XtendActivator
The internal activator is generated code. But we need to register a listener to theme changes. This is done with the new activator.

2020-11-20 12:34 UTC, kthoms commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendActivator.java
> +@SuppressWarnings("restriction")
opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=568990

2020-11-20 12:35 UTC, cdietrich approved these changes

2020-11-20 12:36 UTC, kthoms commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendThemeManager.java
> +public class XtendThemeManager implements EventHandler {
ITheme & IThemeManager

2020-11-20 12:36 UTC, merged