[#789] Find *.xtend test cases on the package level.
eclipse/xtext-xtend pull request #969
Opened 2019-11-27 17:49 UTC by miklossy

- Modify the plugin.xml of the Xtend IDE to ensure that the
JavaElementDelegateJunitLaunch is invoked when right clicking on a java
package.
- Modify the XtendJavaElementDelegateJunitLaunch to provide a proper
implementation of the getJavaElementForPackage(IPackageFragment) method
to deliver the corresponding java package in the xtend-gen folder.

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

2019-11-27 18:49 UTC, cdietrich requested changes
this seems to destry the run on the file and within the file (rightclick)

2019-11-27 19:52 UTC, miklossy commented
You mean that the JUnit Menu is not there at all?

2019-11-27 20:04 UTC, cdietrich commented
Yes no entries at all

2019-11-28 06:31 UTC, miklossy commented
@cdietrich you were right, the menus indeed have been disappeared. I updated the PR, now it should be fine. Please check again. Thank you!

2019-11-28 07:12 UTC, cdietrich commented
@miklossy selecting a source folder is still not working.

2019-11-28 09:52 UTC, miklossy commented
@cdietrich Currently, when selecting a source folder, the JUnit Menu (provided by JDT) appears, but selecting it reports that no JUnit test cases are found.

Making the `org.eclipse.jdt.core.IPackageFragmentRoot` (similar to the `org.eclipse.jdt.core.IPackageFragment` class) adaptable, would results that two JUnit menus will be present (one will work, but the one provided by JDT will not).

2019-11-28 10:09 UTC, cdietrich commented
@miklossy  why dont i get two entries for packages then?

2019-11-28 10:27 UTC, miklossy commented
@cdietrich JDT offers no JUnit Menu on packages containing no java files. The Xtend IDE offers the JUnit Menu only on packages containing no java files but at least one `*.xtend` file. See `boolean containsOnlyXtendFiles(IPackageFragment packageFragment)` method in the PR.

2019-11-28 10:50 UTC, cdietrich commented
No I mean a package with one xtend and one java file

2019-11-28 11:26 UTC, miklossy commented
When this PR is applied, the JUnit Menu is offered on packages containing no java files but at least one *.xtend file, see also [screenshot](https://user-images.githubusercontent.com/20393472/56714492-403a4900-6735-11e9-97c1-086d6eee3ef4.png) attached to the issue #789

2019-11-28 11:29 UTC, miklossy commented
If you remove the containsOnlyXtendFiles(packageFragment) guard from the PR than you will get two JUnit menu on packages containing both java and xtend files:
![screenshot](https://user-images.githubusercontent.com/20393472/69802825-bc6ca180-11da-11ea-9479-a503573a6d96.png)

2019-11-28 11:29 UTC, cdietrich commented
yes but what i dont understand: why cant the very same concept not be ported to src folders?
cause jdt alsways shows something. even if there is no java file?

2019-11-28 11:30 UTC, miklossy commented
JDT shows nothing on packages containing no java files. But JDT shows the JUnit menu point on source folders even if they contain no java files.

2019-11-28 11:31 UTC, cdietrich commented
:(

2019-11-28 11:31 UTC, cdietrich commented
i really hate what jdt does here

2019-11-28 11:31 UTC, cdietrich commented
@szarnekow what do you think?

2019-11-28 11:32 UTC, miklossy commented
We should investigate the use case with the source folders later on. Currently for me the use case on packages is the important one.

2019-11-28 12:40 UTC, cdietrich commented
behaviour is different between junit 4 (executes java only) and 5 (executes both)
and between packages and src folders

2019-12-03 16:25 UTC, szarnekow commented
Is there already a consensus on what we want to achieve?
I'd vote for running the Xtend tests and the Java tests when selecting either a source folder or a package from a source folder.
If a xtend-gen or package from xtend-gen is selected, we should probably not try to outsmart anything and just do what JDT does in those cases.
Junit4 and Junit5 should behave identically.

2019-12-04 07:51 UTC, miklossy commented
> 
> 
> Is there already a consensus on what we want to achieve?
The goal of this PR is to improve the Xtend IDE behavior on packages containing only `*.xtend` files.
> I'd vote for running the Xtend tests and the Java tests when selecting either a source folder or a package from a source folder.
JDT behaves differently when selecting a source folder and a package containing no java test cases:
- On source folder selection, JDT already provides a JUnit menu, when clicking that, there is a message that no JUnit test cases are found. If the Xtend IDE would provide its own JUnit menu, there would be two JUnit menus offered.
- On package selection, JDT does not provide any menu, so that the Xtend IDE can provide its own JUnit menu.
> If a xtend-gen or package from xtend-gen is selected, we should probably not try to outsmart anything and just do what JDT does in those cases.
- Its already happens, see the `containsOnlyXtendFiles` guard.
> Junit4 and Junit5 should behave identically.
There is a different behaviour on packages containing both `*.java` and `*.xtend` files.
- In case of Junit4, only the test cases implemented in Xtend will be executed.
- In case of Junit5, both test cases will be executed.
I like the Junit5 behaviour here, but to make that also work for Junit4, the JDT behaviour should be improved here, I guess.

2019-12-04 07:56 UTC, cdietrich commented
@miklossy i cannot follow you: here is was JDT does on package

![junit_on_package](https://user-images.githubusercontent.com/238736/70123911-e65b1380-1673-11ea-901f-0c76b7b1e104.png)

2019-12-04 08:00 UTC, miklossy commented
@cdietrich I mean if you selected a package containing **no java test cases**, there is no JDT JUnit menu offered.

2019-12-04 08:08 UTC, cdietrich commented
yes but i wonder how this is calculated and if we can take part there.
my expectation is:

if there is a  java junit test and a xtend unit test both get executed

2019-12-04 08:09 UTC, miklossy commented
> 
> 
> yes but i wonder how this is calculated and if we can take part there.
> my expectation is:
> 
> if there is a java junit test and a xtend unit test both get executed

This should already be the case for `Junit5`, right? only `Junit4` behaves different. Can you confirm that?

2019-12-04 08:13 UTC, cdietrich commented
will do when i find the time to examine

2020-01-17 12:20 UTC, cdietrich commented
@szarnekow @miklossy how to proceed?

2020-01-18 10:13 UTC, miklossy commented
I would like to merge this as soon as possible and collect feedback from the community afterwards.

2020-01-18 10:22 UTC, szarnekow requested changes

2020-01-18 10:22 UTC, szarnekow commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/launching/XtendJavaElementDelegateJunitLaunch.java
> +		if (project instanceof IJavaProject) {
This should use the outputconfig instead of hard coded paths

2020-01-18 12:14 UTC, miklossy commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/launching/XtendJavaElementDelegateJunitLaunch.java
> +		if (project instanceof IJavaProject) {
Thanks for the feedback @szarnekow ! I udpated the PR to use the `org.eclipse.xtext.builder.EclipseOutputConfigurationProvider` instead of the hard-coded path.

2020-01-18 13:24 UTC, szarnekow commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/launching/XtendJavaElementDelegateJunitLaunch.java
> +		Set<OutputConfiguration> outputConfigurations = outputConfigurationProvider.getOutputConfigurations();
Instead of using the first output folder, I'd recommend to return the output folder, that matches the original package fragment root.

2020-01-19 14:33 UTC, miklossy commented
I extended the PR with corresponding `XtendJavaElementDelegateJunitLaunchTest` test
cases.

2020-01-19 14:36 UTC, miklossy commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/launching/XtendJavaElementDelegateJunitLaunch.java
> +		Set<OutputConfiguration> outputConfigurations = outputConfigurationProvider.getOutputConfigurations();
As far as I can see, the `OutputConfiguration.getOutputDirectory` method returns only the name of the output folder (in this case `xtend-gen`), so there is nothing with that I could compare the original package fragment root. I would suggest to keep that implementation as it is and improve that later on on demand.

2020-01-19 14:47 UTC, szarnekow commented on org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/launching/XtendJavaElementDelegateJunitLaunch.java
> +		Set<OutputConfiguration> outputConfigurations = outputConfigurationProvider.getOutputConfigurations();
As far as I can tell, this will break immediately if a Xtend is used in a maven project with `src/main/java` and `src/test/java` source folders. You may want to take inspiration from the org.eclipse.xtend.ide.builder.SourceRelativeFileSystemAccess

2020-01-20 13:45 UTC, miklossy commented
@szarnekow You are absolutly right, unforunatly this solution does not work for maven project with `src/test/java` source folders:
![screenshot](https://user-images.githubusercontent.com/20393472/72731181-72c58500-3b93-11ea-9801-982556454d13.png)

2020-01-20 13:45 UTC, closed without merging