[977] Further refinement of the checkJUnitMethodReturnType Xtend validation…
eclipse/xtext-xtend pull request #978
Opened 2019-12-12 14:36 UTC by sailingKieler

… rule incorporating the test runner setting.

Signed-off-by: Christian Schneider <christian.schneider@typefox.io>

2019-12-12 14:38 UTC, sailingKieler commented
See also #977.

2019-12-12 14:45 UTC, dhuebner approved these changes

2019-12-12 14:52 UTC, szarnekow requested changes

2019-12-12 14:52 UTC, szarnekow commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +	protected boolean classUsesCustomRunner(XtendTypeDeclaration clazz) {
Since `@RunWith` is also `@Inherited`, we need to check the super type hierarchy.

2019-12-12 14:52 UTC, szarnekow commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +				final Iterable<JvmAnnotationReference> annRefs = filter(
I think imperative coding style would greatly help to follow the logic here. But that's a matter of taste.

2019-12-12 14:52 UTC, szarnekow commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +				final Iterable<JvmAnnotationReference> annRefs = filter(
This looks like `XAnnotationUtil.findAnnotation` or `org.eclipse.xtext.common.types.util.AnnotationLookup.findAnnotation(JvmAnnotationTarget, String)`

2019-12-12 14:52 UTC, szarnekow commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +		if(!classUsesCustomRunner(function.getDeclaringType()) && hasJUnitAnnotation(operation)) {
This should probably check operation.getDeclaringType rather than function.getDeclaringType

2019-12-12 15:01 UTC, sailingKieler commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +		if(!classUsesCustomRunner(function.getDeclaringType()) && hasJUnitAnnotation(operation)) {
right, makes sense.

2019-12-12 15:05 UTC, sailingKieler commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +				final Iterable<JvmAnnotationReference> annRefs = filter(
true!

2019-12-12 15:05 UTC, sailingKieler commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +	protected boolean classUsesCustomRunner(XtendTypeDeclaration clazz) {
Good point, thanks!

2019-12-12 15:09 UTC, sailingKieler commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +	protected boolean classUsesCustomRunner(XtendTypeDeclaration clazz) {
@szarnekow is there any helper method providing all the super types?

2019-12-12 15:13 UTC, szarnekow commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +	protected boolean classUsesCustomRunner(XtendTypeDeclaration clazz) {
Yes, there is `org.eclipse.xtext.common.types.util.RawSuperTypes`

2019-12-12 15:16 UTC, sailingKieler commented on org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java
> +	protected boolean classUsesCustomRunner(XtendTypeDeclaration clazz) {
right, Thanks. Didn't work with Xbase/the types stuff for quite some time...

2019-12-16 10:13 UTC, sailingKieler commented
Pushed update corresponding to your remarks.

2019-12-16 10:25 UTC, szarnekow requested changes
I don't think we'll find an easy to understand consensus on the validation. E.g. this change will miss all subtypes of BlockJunit4ClassRunner.
Maybe we should rather make the validation itself configurable such that users who implemented own runners can disable it?
Or it should become smart enough and closer to the runtime semantics of Junit4.

2019-12-16 10:25 UTC, szarnekow commented on org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
> +			class MyRunner extends org.eclipse.xtext.testing.XtextRunner {
I'm not sure about this test expectation. `MyRunner` extends (transitively) `org.junit.runners.BlockJUnit4ClassRunner` which has `org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(List<Throwable>)` and will throw if a test method is not `void`.

2019-12-16 10:46 UTC, sailingKieler commented on org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
> +			class MyRunner extends org.eclipse.xtext.testing.XtextRunner {
Correct. But If I add an override like
```
override protected validatePublicVoidNoArgMethods(Class<? extends Annotation> annotation, boolean isStatic, List<Throwable> errors) {
}
```
it doesn't.

To be honest, I don't see why Xtend shall enforce the defaults of a library. Is there any other library out there for which you would accept that?
I can see the point that a compile time check is preferable over a runtime check in practice, and that's why the checks are still active in the default case.

2019-12-16 10:59 UTC, sailingKieler commented on org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
> +			class MyRunner extends org.eclipse.xtext.testing.XtextRunner {
(and for completeness:) ...or
```
override protected collectInitializationErrors(List<Throwable> errors) {
}
```

2019-12-16 11:03 UTC, szarnekow commented on org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
> +			class MyRunner extends org.eclipse.xtext.testing.XtextRunner {
I understand what you are saying. But please also consider the first sentence of the `org.junit.Test` annotation's Javadoch: `The Test annotation tells JUnit that the public void method to which it is attached can be run as a test case.` So I'm not sure that whatever test runner you are using is violating the contract of the Test annotation.

2019-12-16 11:19 UTC, miklossy commented on org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
> +			class MyRunner extends org.eclipse.xtext.testing.XtextRunner {
Making the validation severity configurable could be the right way to go as suggested by @dhuebner in his previous comment: https://github.com/eclipse/xtext-xtend/issues/516#issuecomment-518571016

2019-12-16 12:36 UTC, sailingKieler commented on org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/JUnitMethodReturnTypeValidationTest.xtend
> +			class MyRunner extends org.eclipse.xtext.testing.XtextRunner {
> I understand what you are saying. But please also consider the first sentence of the `org.junit.Test` annotation's Javadoch: `The Test annotation tells JUnit that the public void method to which it is attached can be run as a test case.` So I'm not sure that whatever test runner you are using is violating the contract of the Test annotation.

That's indeed true ... hmmm.

2020-01-08 13:33 UTC, cdietrich commented
i have no clue how to procede with this

2020-01-08 15:52 UTC, szarnekow commented
I think making the validation configurable would be a good compromise. In the current shape, I'd not approve this PR.

2020-01-20 14:05 UTC, miklossy commented
> 
> 
> I think making the validation configurable would be a good compromise. In the current shape, I'd not approve this PR.

@sailingKieler Could you please update the PR as @szarnekow and @dhuebner suggested?

2020-01-20 14:06 UTC, miklossy requested changes
I would also prefer to make the validation rule configurable, so that everyone can configure that according to his/her custom needs.

2020-01-21 09:06 UTC, sailingKieler commented
Although that I'm still convinced that it shouldn't be Xtend's job to implement and enforce semantics of any framework's client API, the remark in https://github.com/eclipse/xtext-xtend/pull/978#discussion_r358172450 convinced me to better switch to a custom marker annotation.
Consequently, I close this PR.

2020-01-21 09:06 UTC, closed without merging